export const discos = [
    { id: 1, nombre: 'Tocsin', artista: 'Xmal Deutschland', genero: 'Darkwave', anio: '1984', destacada: 'Tag für Tag', img: 'img/tocsin.png', resena: 'Este disco lo tuve pegado dos meses, dos meses siendo lo que escuchaba mayormente, así de bueno es. Tiene sus momentos bailables a la vez de lugubres, combinándose de manera excelente y más de una vez he querido interpretar esa música en un escenario.' },
    { id: 2, nombre: 'Origin of Symmetry', artista: 'Muse', genero: 'Rock Progresivo', anio: '2001', destacada: 'Micro-Cuts', img: 'img/symmetry.png', resena: 'Uno de mis discos favoritos de una de mis bandas favoritas. Si hay algo que Muse logra hacer a la perfección es convertir una canción en una ópera moderna, en un momento épico musical y se nota que los músicos presentes saben y disfrutan lo que hacen' },
    { id: 3, nombre: 'That Total Age', artista: 'Nitzer Ebb', genero: 'Industrial', anio: '1987', destacada: 'Violent Playground', img: 'img/total.png', resena: 'Música para hacer ejercicio o dar una caminata y terminar andando por la vida lista para enfrentarte a lo que sea; ideal para cuando tienes que hacer algo importante y necesitas energía. Obviamente, también tiene su espacio para la pista de baile ¡Que tu cuerpo aprenda!' },
    { id: 4, nombre: 'Koloss', artista: 'Meshuggah', genero: 'Metal Progresivo', anio: '2012', destacada: 'I Am Colossus', img: 'img/koloss.png',  resena: 'La música de Meshuggah está fríamente calculada, es un orden dentro del caos y un caos dentro del orden. Realmente manejan los intrumentos como si fuera una avalancha. Si quiere saber más sobre su creación, hay un documental al respecto en Youtube, donde los integrantes de la banda participan. Nota curiosa: "I am Collosus" fue mi tono de llamada de mi celular un tiempo' },
    { id: 5, nombre: 'This is Hardcore', artista: 'Pulp', genero: 'Alternativo', anio: '1998', destacada: 'This is Hardcore', img: 'img/hardcore.png', resena: 'El disco que refleja el cansancio, la ansiedad y el desdén ante la fama del britpop. Un disco elegante dentro de lo amargo que refleja, se escucha muchísimo mejor de noche.' },
    { id: 6, nombre: 'Blue Blood', artista: 'X Japan', genero: 'Metal Progresivo', anio: '1989', destacada: 'X', img: 'img/blueblood.png', resena: 'Este disco no tiene ningún tema malo, todos tienen algo que decir y demuestran la rapidez y teatralidad que tiene X-Japan a la hora de tocar música. Si le gusta la música proveniente de Japón, vaya a escuchar este disco y varios más de ellos después de leer esta reseña.' },
    { id: 7, nombre: 'Front by Front', artista: 'Front 242', genero: 'Industrial', anio: '1988', destacada: 'Welcome to Paradise', img: 'img/frontbyfront.png', resena: 'Una de las bandas insignia del EBM y el Industrial, creando ritmos bailables a la vez de pesados y añadiendo los samples recurrentes del género. Un infaltable para escuchar y entender el impacto de estos géneros en los 80s. Nota curiosa: La intro de una de sus canciones sale como referencia en una canción de Axé.'},
    { id: 8, nombre: 'Freak Perfume', artista: 'Diary of Dreams', genero: 'Darkwave', anio: '2002', destacada: 'Traumtänzer', img: 'img/freakperfume.png', resena: 'Un disco melancólico con el que igual puedes bailar, una mezcla bien curiosa que Diary of Dreams lleva perfeccionando con los años. Canciones que tratan de la pérdida, la confusión, el duelo, entre otros sentimientos que se reflejan sobretodo en la voz de Adrian Hates.' },
    { id: 9, nombre: 'Orchid', artista: 'Opeth', genero: 'Metal Progresivo', anio: '1995', destacada: 'The Twilight Is My Robe', img: 'img/orchid.png', resena: 'Opeth mostrando desde sus inicios una mezcla entre pasajes musicales extensos, voces guturales y letras poéticas. Este disco lo escuché dando un paseo y fue una de las mejores cosas para escuchar mientras presenciaba un atardecer.' },
    { id: 10, nombre: 'You Could Have it So Much Better', artista: 'Franz Ferdinand', genero: 'Alternativo', anio: '2005', destacada: 'You Could Have it So Much Better', img: 'img/youcouldhaveit.png', resena: 'Este disco salió y lo escuché cuando estaba en la educación media y la música, estilismo y referencias gráficas de Franz Ferdinand siempre me gustaron mucho. Energéticos, elegantes, provocadores, todo eso y más. Definitivamente una buena influencia en mis años de adolescencia.' },
]